/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs338.gui;

/**
 *
 * @author MDEY
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RibbonPanel = new javax.swing.JPanel();
        RibbonClipboardPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        CanvasPanel = new javax.swing.JPanel();
        MainCanvas = new java.awt.Canvas();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuBarFileButton = new javax.swing.JMenu();
        FileMenuNew = new javax.swing.JMenuItem();
        FileMenuOpen = new javax.swing.JMenuItem();
        FileMenuSave = new javax.swing.JMenuItem();
        MenuBarViewButton = new javax.swing.JMenu();
        ViewMenuZoom = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RibbonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Home"));

        RibbonClipboardPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clipboard", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));

        javax.swing.GroupLayout RibbonClipboardPanelLayout = new javax.swing.GroupLayout(RibbonClipboardPanel);
        RibbonClipboardPanel.setLayout(RibbonClipboardPanelLayout);
        RibbonClipboardPanelLayout.setHorizontalGroup(
            RibbonClipboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );
        RibbonClipboardPanelLayout.setVerticalGroup(
            RibbonClipboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RibbonPanelLayout = new javax.swing.GroupLayout(RibbonPanel);
        RibbonPanel.setLayout(RibbonPanelLayout);
        RibbonPanelLayout.setHorizontalGroup(
            RibbonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RibbonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RibbonClipboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(756, Short.MAX_VALUE))
        );
        RibbonPanelLayout.setVerticalGroup(
            RibbonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RibbonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RibbonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RibbonClipboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        javax.swing.GroupLayout CanvasPanelLayout = new javax.swing.GroupLayout(CanvasPanel);
        CanvasPanel.setLayout(CanvasPanelLayout);
        CanvasPanelLayout.setHorizontalGroup(
            CanvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CanvasPanelLayout.setVerticalGroup(
            CanvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainCanvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        MenuBarFileButton.setText("File");
        MenuBarFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarFileButtonActionPerformed(evt);
            }
        });

        FileMenuNew.setText("New");
        FileMenuNew.setToolTipText("");
        FileMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuNewActionPerformed(evt);
            }
        });
        MenuBarFileButton.add(FileMenuNew);

        FileMenuOpen.setText("Open");
        MenuBarFileButton.add(FileMenuOpen);

        FileMenuSave.setText("Save");
        MenuBarFileButton.add(FileMenuSave);

        jMenuBar1.add(MenuBarFileButton);

        MenuBarViewButton.setText("View");

        ViewMenuZoom.setText("Zoom");
        ViewMenuZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMenuZoomActionPerformed(evt);
            }
        });
        MenuBarViewButton.add(ViewMenuZoom);

        jMenuBar1.add(MenuBarViewButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CanvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RibbonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RibbonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CanvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBarFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarFileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuBarFileButtonActionPerformed

    private void FileMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileMenuNewActionPerformed

    private void ViewMenuZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMenuZoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewMenuZoomActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CanvasPanel;
    private javax.swing.JMenuItem FileMenuNew;
    private javax.swing.JMenuItem FileMenuOpen;
    private javax.swing.JMenuItem FileMenuSave;
    private java.awt.Canvas MainCanvas;
    private javax.swing.JMenu MenuBarFileButton;
    private javax.swing.JMenu MenuBarViewButton;
    private javax.swing.JPanel RibbonClipboardPanel;
    private javax.swing.JPanel RibbonPanel;
    private javax.swing.JMenuItem ViewMenuZoom;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
